import { makeStyles } from '@material-ui/core';

const DRAWER_WIDTH = 400;

export default makeStyles((theme) => ({
  drawer: {
    width: DRAWER_WIDTH,
  },
  drawerPaper: {
    backgroundColor: '#E8EDF7',
    width: DRAWER_WIDTH,
  },
  logo: {
    height: '135px',
    marginTop: '-8px',
    marginLeft: '103px',
    backgroundColor: '#E8EDF7',
    marginRight: '157px',
  },
  list: {
    marginTop: '42px',
    marginRight: '172px',
    marginLeft: '66px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
  },
  link: {
    textDecoration: 'none',
  },
  iconContainer: {
    width: '36px',
    height: '36px',
    // backgroundColor: 'rgba(134, 169, 224, 0.3)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    // borderRadius: '15px',
    marginRight: '64px',
    marginLeft: '36px',
  },
  icon: {
    height: '36px',
    width:'36px',
    position: 'absolute',
    left: '0px',
    top: '0px',

  },
  listItem: {
    borderLeft: '67px', 
    color: '#0F2C4C',
    display: 'flex',
    // flexDirection: 'column',
    // alignItems: 'flex-start',
    // position: 'absolute',
    padding: '0',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '24px',
    lineHeight: '28px',
    margin: `30px 0px`,
  },
  listItemActive: {
    backgroundColor: 'rgba(196, 196, 196, 0.24)',
    fontWeight: 700,
    borderRight: `3.87px solid #0F2C4C`,
    width: '327.5px',
    height: '80px',
    '&:hover': {
      backgroundColor: 'rgba(196, 196, 196, 0.24)',
    },
    // '& $iconContainer': {
    //   backgroundColor: '#E8EDF7',
    // },
  },
  badge: {
    position: 'absolute',
    right: '15px',
    top: '50%',
    transform: 'translateY(-50%)',
    // backgroundColor: '#1891DA',
    color: '#fff'   ,
    fontFamily: 'Roboto',
    width: '20px',
    height: '20px',
    textAlign: 'center',
    borderRadius: '50%',
    fontWeight: 'bold',
  },
  profileInfo: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#F6F7FB',
    boxShadow: '0px 2px 5px rgba(0, 0, 0, 0.15)',
    borderRadius: '5px',
    width: `${DRAWER_WIDTH - 50}px`,
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 'auto',
    marginBottom: '20px',
    paddingTop: '20px',
    paddingBottom: '20px',
    textTransform: 'none',
  },
  profileInfoText: {
    color: theme.palette.spaceBlue,
  },
  profilePhoto: {
    marginRight: '10px',
    width: '42px',
    height: '42px',
  },
}));
